# Generated by Django 6.0 on 2025-12-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student',
        ),
    ]
